Objetivo 1
JaimeGM96/Practica-IV pull request #5
Opened 2021-09-30 09:25 UTC by JaimeGM96

2021-09-30 09:27 UTC, JaimeGM96 commented
PR listo para revisión.

2021-10-01 15:29 UTC, JJ requested changes
Por favor, tratad de entender qué es un hito y un producto mínimamente viable. Repasa lo que se ha dicho sobre el tema y corrígelo.

2021-10-01 15:29 UTC, JJ commented on docs/documentacion.md
> +- HU1: Quiero disponer cada mañana del precio de las frutas y verduras de las cooperativas de la zona de ese día.
Esto es sólo búsqueda, aunque puede ser necesario como es natural para otras HUs

2021-10-01 15:29 UTC, JJ commented on docs/documentacion.md
> +- HU3: Quiero disponer cada mañana del precio de las frutas y verduras de temporadas pasadas de las cooperativas de la zona.
Esta es más o menos igual que H1

2021-10-13 16:08 UTC, JaimeGM96 commented
He vuelto a revisar todo y espero que esta vez haya entendido los PMVs. He modificado los milestones y los issues. Espero su confirmación.

2021-10-14 05:31 UTC, JJ commented on docs/documentacion.md
> +- [HU3](https://github.com/JaimeGM96/Practica-IV/issues/4): Quiero disponer cada mañana del precio de las frutas y verduras de temporadas pasadas de las cooperativas de la zona.
De repente han aparecido 3 clases más que no están aquí. Sigues sin poner un *user journey*, que te ayudaría a saber qué es lo que cada usuario quiere y como. No tienes tampoco diferentes tipos de clientes ni qué busca cada uno.

2021-10-15 10:48 UTC, JaimeGM96 commented
He actualizado el README con la nueva lógica de negocio y he creado un nuevo issue con una nueva clase necesaria en la implementación de la aplicación.

2021-10-16 08:00 UTC, JJ commented on docs/documentacion.md
> +Si el agricultor desea vender varios productos diferentes, lo indicará en el sistema y se le mostrará la ruta más optima.
Por favor, controla las faltas de ortografía.

2021-10-16 09:28 UTC, merged